import { useEffect, useMemo, useState } from 'react'
import { Bell, BellRing, ShieldAlert } from 'lucide-react'
import { EmptyState } from '@/components/EmptyState'
import { useProfile } from '@/features/auth/useProfile'
import { useNotificationsContext } from '@/features/notifications/NotificationsContext'
import { NOTIFICATION_KIND_META, type NotificationKind } from '@/features/notifications/notificationKindMeta'
import type { NotificationFeedRow } from '@/features/notifications/notificationsService'
import { pushService, type PushPermissionState } from '@/features/notifications/pushService'
import { timeAgo } from '@/lib/datetime'
import { useLanguage } from '@/i18n/LanguageContext'

type Filter = 'all' | NotificationKind

const FILTERS: { key: Filter; labelKey: string }[] = [
  { key: 'all', labelKey: 'notifications.filterAll' },
  { key: 'late_clock_in', labelKey: 'notifications.filterLate' },
  { key: 'idling_too_long', labelKey: 'notifications.filterIdling' },
  { key: 'ineffective_visit', labelKey: 'notifications.filterIneffective' },
  { key: 'late_clock_out', labelKey: 'notifications.filterLateClockOut' },
]

/**
 * Super-admin-only activity monitoring: late clock-ins, idling too long,
 * and ineffective (too-short) visits, system-generated by DB triggers/a
 * scheduled job (see the notifications_center migration) -- never written
 * from the client, and never shown to the employee the notification is
 * about. Self-guards on is_super_admin exactly like SettingsPage does,
 * since this route is reachable by URL regardless of nav visibility.
 */
export function NotificationsPage() {
  const { profile, loading: profileLoading } = useProfile()
  const { t } = useLanguage()

  if (profileLoading) {
    return (
      <div className="mx-auto max-w-lg space-y-2 p-4 md:max-w-2xl">
        <div className="h-16 animate-pulse rounded-xl2 bg-neutral-100" />
        <div className="h-16 animate-pulse rounded-xl2 bg-neutral-100" />
      </div>
    )
  }

  if (!profile?.is_super_admin) {
    return (
      <div className="mx-auto flex max-w-lg flex-col items-center px-6 pt-16 text-center md:max-w-2xl">
        <ShieldAlert className="h-10 w-10 text-neutral-300" />
        <p className="mt-4 text-sm text-neutral-500">{t('notifications.adminOnly')}</p>
      </div>
    )
  }

  return <NotificationsFeed />
}

function NotificationsFeed() {
  const { notifications, loading, error, markRead } = useNotificationsContext()
  const { t } = useLanguage()
  const [filter, setFilter] = useState<Filter>('all')

  const filtered = useMemo(
    () => (filter === 'all' ? notifications : notifications.filter((n) => n.kind === filter)),
    [notifications, filter]
  )

  return (
    <div className="mx-auto max-w-lg pb-6 md:max-w-2xl">
      <div className="px-4 pt-4 md:px-8">
        <PushNotificationsCard />

        <div className="mt-4 flex gap-1 rounded-full bg-neutral-100 p-1">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              onClick={() => setFilter(f.key)}
              className={`flex-1 whitespace-nowrap rounded-full px-3 py-2 text-sm font-semibold tap-target ${
                filter === f.key ? 'bg-white text-neutral-900 shadow-sm' : 'text-neutral-500'
              }`}
            >
              {t(f.labelKey)}
            </button>
          ))}
        </div>

        {error && <p className="mt-3 rounded-lg bg-status-danger/10 px-3 py-2 text-sm text-status-danger">{error}</p>}

        {loading ? (
          <div className="mt-4 space-y-2">
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="mt-4">
            <EmptyState icon={Bell} title={t('notifications.emptyTitle')} body={t('notifications.emptyBody')} />
          </div>
        ) : (
          <div className="mt-4 space-y-2">
            {filtered.map((n) => (
              <NotificationRow
                key={n.id}
                notification={n}
                onOpen={() => {
                  if (n.id && !n.read_at) void markRead(n.id)
                }}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

/**
 * Lets a super admin subscribe THIS device to Web Push for the same
 * anomaly notifications shown below -- an additional delivery channel, not
 * a replacement (the feed above is unaffected either way). See
 * pushService.ts and supabase/functions/push-notify-admins.
 */
function PushNotificationsCard() {
  const [state, setState] = useState<PushPermissionState | 'loading'>('loading')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [testSent, setTestSent] = useState(false)

  useEffect(() => {
    pushService.getState().then(setState)
  }, [])

  async function handle(action: () => Promise<void>) {
    setBusy(true)
    setError(null)
    setTestSent(false)
    try {
      await action()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong.')
    } finally {
      setState(await pushService.getState())
      setBusy(false)
    }
  }

  if (state === 'loading' || state === 'unsupported') return null

  return (
    <div className="mb-2 rounded-xl2 border border-neutral-200 bg-white p-3.5 shadow-card dark:border-neutral-700">
      <p className="flex items-center gap-2 text-sm font-semibold text-neutral-800">
        <BellRing className="h-4 w-4 text-neutral-400" />
        Push Notifications
      </p>
      <p className="mt-1 text-xs text-neutral-400">
        {state === 'subscribed'
          ? 'This device will get a push the moment one of these fires, even when the app is closed.'
          : state === 'denied'
            ? 'Notifications are blocked for this app in your browser/OS settings.'
            : 'Get a push on this device the moment one of these fires, even when the app is closed.'}
      </p>

      {error && <p className="mt-2 rounded-lg bg-status-danger/10 px-3 py-2 text-xs text-status-danger">{error}</p>}
      {testSent && <p className="mt-2 text-xs font-medium text-status-working">Test push sent -- check this device.</p>}

      <div className="mt-2.5 flex flex-wrap gap-2">
        {state !== 'subscribed' && state !== 'denied' && (
          <button
            onClick={() => handle(() => pushService.subscribe())}
            disabled={busy}
            className="rounded-xl bg-neutral-900 px-4 py-2 text-xs font-semibold text-white tap-target disabled:opacity-40"
          >
            Enable
          </button>
        )}
        {state === 'subscribed' && (
          <>
            <button
              onClick={() => handle(() => pushService.previewLocalNotification())}
              disabled={busy}
              className="rounded-xl border border-neutral-200 px-4 py-2 text-xs font-semibold text-neutral-700 tap-target disabled:opacity-40 dark:border-neutral-700 dark:text-neutral-300"
            >
              Preview
            </button>
            <button
              onClick={() =>
                handle(async () => {
                  await pushService.sendTestPush()
                  setTestSent(true)
                })
              }
              disabled={busy}
              className="rounded-xl border border-neutral-200 px-4 py-2 text-xs font-semibold text-neutral-700 tap-target disabled:opacity-40 dark:border-neutral-700 dark:text-neutral-300"
            >
              Send test push
            </button>
            <button
              onClick={() => handle(() => pushService.unsubscribe())}
              disabled={busy}
              className="rounded-xl px-4 py-2 text-xs font-semibold text-status-danger tap-target disabled:opacity-40"
            >
              Disable
            </button>
          </>
        )}
      </div>
    </div>
  )
}

function NotificationRow({ notification, onOpen }: { notification: NotificationFeedRow; onOpen: () => void }) {
  const { t, language } = useLanguage()
  const meta = notification.kind ? NOTIFICATION_KIND_META[notification.kind] : null
  const unread = !notification.read_at

  return (
    <button
      onClick={onOpen}
      className={`flex w-full items-start gap-3 rounded-xl2 bg-white p-3.5 text-left shadow-card tap-target ${unread ? '' : 'opacity-70'}`}
    >
      <span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${meta?.tone ?? 'bg-neutral-100 text-neutral-500'}`}>
        {meta ? <meta.icon className="h-4.5 w-4.5" /> : <Bell className="h-4.5 w-4.5" />}
      </span>
      <span className="min-w-0 flex-1">
        <span className="flex items-center gap-1.5">
          <span className={`truncate text-sm ${unread ? 'font-semibold text-neutral-900' : 'font-medium text-neutral-700'}`}>
            {notification.user_name ?? t('notifications.unknownUser')}
          </span>
          {unread && <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" aria-label="Unread" />}
        </span>
        <span className="mt-0.5 block text-xs font-medium uppercase tracking-wide text-neutral-400">
          {meta ? t(meta.labelKey) : notification.kind}
        </span>
        <span className="mt-1 block text-sm text-neutral-600">{notification.comment}</span>
        {notification.customer_name && <span className="mt-0.5 block text-xs text-neutral-400">{notification.customer_name}</span>}
        <span className="mt-1 block text-xs text-neutral-400">
          {notification.created_at ? timeAgo(notification.created_at, undefined, language) : ''}
        </span>
      </span>
    </button>
  )
}
