import { useMemo, useState } from 'react'
import { Bell, ShieldAlert } from 'lucide-react'
import { EmptyState } from '@/components/EmptyState'
import { useProfile } from '@/features/auth/useProfile'
import { useNotifications } from '@/features/notifications/useNotifications'
import { NOTIFICATION_KIND_META, type NotificationKind } from '@/features/notifications/notificationKindMeta'
import type { NotificationFeedRow } from '@/features/notifications/notificationsService'
import { timeAgo } from '@/lib/datetime'

type Filter = 'all' | NotificationKind

const FILTERS: { key: Filter; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'late_clock_in', label: 'Late Clock-In' },
  { key: 'idling_too_long', label: 'Idling' },
  { key: 'ineffective_visit', label: 'Ineffective Visit' },
]

/**
 * Super-admin-only activity monitoring: late clock-ins, idling too long,
 * and ineffective (too-short) visits, system-generated by DB triggers/a
 * scheduled job (see the notifications_center migration) -- never written
 * from the client, and never shown to the employee the notification is
 * about. Self-guards on is_super_admin exactly like SettingsPage does,
 * since this route is reachable by URL regardless of nav visibility.
 */
export function NotificationsPage() {
  const { profile, loading: profileLoading } = useProfile()

  if (profileLoading) {
    return (
      <div className="mx-auto max-w-lg space-y-2 p-4 md:max-w-2xl">
        <div className="h-16 animate-pulse rounded-xl2 bg-neutral-100" />
        <div className="h-16 animate-pulse rounded-xl2 bg-neutral-100" />
      </div>
    )
  }

  if (!profile?.is_super_admin) {
    return (
      <div className="mx-auto flex max-w-lg flex-col items-center px-6 pt-16 text-center md:max-w-2xl">
        <ShieldAlert className="h-10 w-10 text-neutral-300" />
        <p className="mt-4 text-sm text-neutral-500">Only a super admin can view notifications.</p>
      </div>
    )
  }

  return <NotificationsFeed />
}

function NotificationsFeed() {
  const { notifications, loading, error, markRead } = useNotifications()
  const [filter, setFilter] = useState<Filter>('all')

  const filtered = useMemo(
    () => (filter === 'all' ? notifications : notifications.filter((n) => n.kind === filter)),
    [notifications, filter]
  )

  return (
    <div className="mx-auto max-w-lg pb-6 md:max-w-2xl">
      <div className="px-4 pt-4 md:px-8">
        <div className="flex gap-1 overflow-x-auto rounded-full bg-neutral-100 p-1">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              onClick={() => setFilter(f.key)}
              className={`flex-1 whitespace-nowrap rounded-full px-3 py-2 text-sm font-semibold tap-target ${
                filter === f.key ? 'bg-white text-neutral-900 shadow-sm' : 'text-neutral-500'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        {error && <p className="mt-3 rounded-lg bg-status-danger/10 px-3 py-2 text-sm text-status-danger">{error}</p>}

        {loading ? (
          <div className="mt-4 space-y-2">
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
            <div className="h-20 animate-pulse rounded-xl2 bg-neutral-100" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="mt-4">
            <EmptyState icon={Bell} title="Nothing to see" body="Flagged activity (late clock-ins, idling, ineffective visits) will show up here." />
          </div>
        ) : (
          <div className="mt-4 space-y-2">
            {filtered.map((n) => (
              <NotificationRow
                key={n.id}
                notification={n}
                onOpen={() => {
                  if (n.id && !n.read_at) void markRead(n.id)
                }}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function NotificationRow({ notification, onOpen }: { notification: NotificationFeedRow; onOpen: () => void }) {
  const meta = notification.kind ? NOTIFICATION_KIND_META[notification.kind] : null
  const unread = !notification.read_at

  return (
    <button
      onClick={onOpen}
      className={`flex w-full items-start gap-3 rounded-xl2 bg-white p-3.5 text-left shadow-card tap-target ${unread ? '' : 'opacity-70'}`}
    >
      <span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${meta?.tone ?? 'bg-neutral-100 text-neutral-500'}`}>
        {meta ? <meta.icon className="h-4.5 w-4.5" /> : <Bell className="h-4.5 w-4.5" />}
      </span>
      <span className="min-w-0 flex-1">
        <span className="flex items-center gap-1.5">
          <span className={`truncate text-sm ${unread ? 'font-semibold text-neutral-900' : 'font-medium text-neutral-700'}`}>
            {notification.user_name ?? 'Unknown user'}
          </span>
          {unread && <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" aria-label="Unread" />}
        </span>
        <span className="mt-0.5 block text-xs font-medium uppercase tracking-wide text-neutral-400">{meta?.label ?? notification.kind}</span>
        <span className="mt-1 block text-sm text-neutral-600">{notification.comment}</span>
        {notification.customer_name && <span className="mt-0.5 block text-xs text-neutral-400">{notification.customer_name}</span>}
        <span className="mt-1 block text-xs text-neutral-400">{notification.created_at ? timeAgo(notification.created_at) : ''}</span>
      </span>
    </button>
  )
}
