import { supabase } from '@/lib/supabase'
import type { Tables } from '@/types/database.types'

export type NotificationFeedRow = Tables<'notification_feed'>

/**
 * Super-admin-only activity notifications (late clock-in, idling too long,
 * ineffective visit) -- system-generated by DB triggers/a scheduled job,
 * never written from the client. `notification_feed` (security_invoker)
 * already joins in the user/customer display names and is RLS-scoped the
 * same as the base `notifications` table (app.can('notification', ...)),
 * so a non-super-admin querying this just gets an empty result, not an error.
 */
export const notificationsService = {
  async list(): Promise<NotificationFeedRow[]> {
    const { data, error } = await supabase.from('notification_feed').select('*').order('created_at', { ascending: false })
    if (error) throw error
    return data ?? []
  },

  async markRead(id: string): Promise<void> {
    const { error } = await supabase.from('notifications').update({ read_at: new Date().toISOString() }).eq('id', id)
    if (error) throw error
  },
}
